---
title: "Assignment 1: Introduction"
author: "Julia Plasynski"
output: pdf_document
geometry: margin=2.54cm
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1. Change "Student Name" on line 3 (above) with your name.
3. Work through the steps, **creating code and output** that fulfill each instruction.
4. Be sure to **answer the questions** in this assignment document.
6. When you have completed the assignment, **Knit** the text and code into a single PDF file.
8. After Knitting, submit the completed exercise (PDF file) to the dropbox in Sakai. Add your last name into the file name (e.g., "Lima_A01_Introduction.Rmd") prior to submission.

The completed exercise is due on <>.

## 1) Discussion Questions

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: During my undergraduate education, I took a course on Biostatistics and we learned how to use SPSS. Last semester, I took the statistics course where I was exposed to R for the first time. I have no used Git before. 

2. Are there any components of the course about which you feel confident?

> Answer: I am confident in the beginning lessons, especially lessons 2, 3, 4, 5, and 6. 

3. Are there any components of the course about which you feel apprehensive?

> Answer: I feel confident in my ability to learn the coding I am not familiar with, however I am nervous about learning most material on my own. I mostly nervous with the later lessons: time series analysis, spatial data analysis, python, and others.


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository  and that you have updated your course README file. 

> Answer: https://github.com/jplasy/Environmental_Data_Analytics_2022


